
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1090,760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(20, 30, 811, 51))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_1.setPlaceholderText("Input your list here ..")
        self.lineEdit_1.setFont(QtGui.QFont("SansSerif", 20))
        self.random_btn = QtWidgets.QPushButton(self.centralwidget)
        self.random_btn.setGeometry(QtCore.QRect(860, 30, 131, 51))
        self.random_btn.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.random_btn.setObjectName("df_btn")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 100, 101, 51))
        self.pushButton_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 100, 101, 51))
        self.pushButton_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(530, 100, 101, 51))
        self.pushButton_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 100, 101, 51))
        self.pushButton_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(50, 100, 101, 51))
        self.pushButton_1.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 180, 441, 251))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 290, 501, 321))
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(550, 290, 511, 311))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 650, 891, 61))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setPlaceholderText("Your sorted list must appeat here ..")
        self.lineEdit_2.setFont(QtGui.QFont("SansSerif", 20))
        self.listview_btn = QtWidgets.QPushButton(self.centralwidget)
        self.listview_btn.setGeometry(QtCore.QRect(930, 650, 131, 61))
        self.listview_btn.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.listview_btn.setObjectName("listview_btn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 0, 551, 21))
        self.label_4.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(890, 180, 160, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalSlider.setMaximum(2)
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setTickPosition(self.horizontalSlider.TicksBelow)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 230, 451, 31))
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(570, 230, 481, 31))
        self.label_6.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(580, 180, 311, 31))
        self.label_7.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(860, 90, 131, 41))
        self.label_8.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(890, 120, 91, 31))
        self.label_9.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 700, 891, 61))
        self.label_10.setStyleSheet("font: 8pt \"MS Shell Dlg 2\";")
        self.label_10.setObjectName("label_10")
        self.res_btn = QtWidgets.QPushButton(self.centralwidget)
        self.res_btn.setGeometry(QtCore.QRect(30, 180, 40, 41))
        self.res_btn.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.res_btn.setObjectName("res_btn")

        self.bgn_btn = QtWidgets.QPushButton(self.centralwidget)
        self.bgn_btn.setGeometry(QtCore.QRect(80, 180, 301, 41))
        self.bgn_btn.setStyleSheet("font: 20pt \"MS Shell Dlg 2\";")
        self.bgn_btn.setObjectName("bgn_btn")

        self.vlBtn = QtWidgets.QPushButton(self.centralwidget)
        self.vlBtn.setGeometry(QtCore.QRect(1000, 30, 71, 51))
        self.vlBtn.setStyleSheet("font: 75 13pt \"MS Shell Dlg 2\";")
        self.vlBtn.setObjectName("vlBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.random_btn.setText(_translate("MainWindow", "GRN"))
        self.pushButton_2.setText(_translate("MainWindow", "Insertion Sort"))
        self.pushButton_3.setText(_translate("MainWindow", "Quick Sort"))
        self.pushButton_4.setText(_translate("MainWindow", "Fusion Sort"))
        self.pushButton_5.setText(_translate("MainWindow", "Bubble Sort"))
        self.pushButton_1.setText(_translate("MainWindow", "Selection Sort"))
        self.listview_btn.setText(_translate("MainWindow", "List View"))
        self.label_4.setText(_translate("MainWindow", "Input space-seperated numbers and choose an algorithm to sort them "))
        self.label_5.setText(_translate("MainWindow", "This is an easy example of the algorithm "))
        self.label_6.setText(_translate("MainWindow", "This is a live visualisation of steps done by the algorithm"))
        self.label_7.setText(_translate("MainWindow", "Adjust the speed of the visualisation"))
        self.label_8.setText(_translate("MainWindow", "Generate Random "))
        self.label_9.setText(_translate("MainWindow", "Numbers"))
        self.label_10.setText(_translate("MainWindow","copyright © 2020.Taha Mohsen Zeidy.All rights reserved."))
        self.vlBtn.setText(_translate("MainWindow", "Validate"))

        self.res_btn.setText(_translate("MainWindow","RES"))
        self.res_btn.setStyleSheet("color:rgb(255, 0, 0);\n""font-weight:bold;""font: 12pt \"MS Shell Dlg 2\";")

        self.bgn_btn.setText(_translate("MainWindow", "Begin Sort"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
